export const META = Object.freeze({
  title: 'myblog.me',
  zh_sub_title: '',
  en_sub_title: '',
  zh_description: '',
  en_description: '',
  url: 'http://myblog.me',
  domain: 'myblog.me',
  author: '',
  primary: 'red',
});

export const IDENTITIES = Object.freeze({
  GOOGLE_ANALYTICS_MEASUREMENT_ID: 'G-R40DDTSYNQ',
  GOOGLE_ADSENSE_CLIENT_ID: 'ca-pub-4710915636313788',
  SENTRY_PUBLIC_DSN: 'https://4a5f194531fe4527879812e4a4d8cf89@o360897.ingest.sentry.io/4505569138966528',
  YOUTUBE_CHANNEL_ID: 'UCoL-j6T28PLSJ2U6ZdONS0w',
  YOUTUBE_CHANNEL_SHORT_ID: '@XXX_v',
  MUSIC_163_BGM_ALBUM_ID: '',
  DOUBAN_USER_ID: '',
  GITHUB_USER_NAME: 'XXX-china',
  TWITTER_USER_NAME: 'XXX7788',
  INSTAGRAM_USERNAME: 'XXX666',
  BTC_ADDRESS: 'bc1qhpdu03tnexkj4xsm3lqzyjdddz6z0rj2n7fsze',
  ETH_ADDRESS: '0xaD556974D449126efdeF23f4FF581861C301cB77',
});

export const VALUABLE_LINKS = Object.freeze({
  RSS: '/rss.xml',
  SITE_MAP: '/sitemap.xml',
  UPTIME_STATUS: 'https://redirect.XXX.me/status',
  NPM_HOMEPAGE: 'https://www.npmjs.com/~XXX',
  PAYPAL: 'https://paypal.me/XXX',
  GITHUB_SPONSORS: `https://github.com/sponsors/${IDENTITIES.GITHUB_USER_NAME}`,
  GITHUB: `https://github.com/${IDENTITIES.GITHUB_USER_NAME}`,
  GITHUB_XXX_ME: 'https://github.com/XXX-china/XXX.me',
  GITHUB_NODEPRESS: 'https://github.com/XXX-china/nodepress',
  GITHUB_XXX_ME_NATIVE: 'https://github.com/XXX-china/XXX.me.native',
  GITHUB_BLOG_STAR_LIST: 'https://github.com/stars/XXX-china/lists/XXX-me',
  MARKDOWN: 'https://daringfireball.net/projects/markdown/',
  GOOGLE_MY_MAP: 'https://www.google.com/maps/d/embed?mid=1sRx6t0Yj1TutbwORCvjwTMgr70r62Z6w&z=3',
  GOOGLE_MY_MAP_KML: 'https://www.google.com/maps/d/u/0/kml?forcekml=1&mid=1sRx6t0Yj1TutbwORCvjwTMgr70r62Z6w',
  DISCORD_GROUP: 'https://redirect.XXX.me/discord-server',
  TELEGRAM_GROUP: 'https://redirect.XXX.me/telegram-group',
  MUSIC_163: `https://music.163.com/#/playlist?id=${IDENTITIES.MUSIC_163_BGM_ALBUM_ID}`,
  YOUTUBE_CHANNEL: `https://www.youtube.com/${IDENTITIES.YOUTUBE_CHANNEL_SHORT_ID}`,
  TELEGRAM: 'https://t.me/XXX',
  OPENSEA: 'https://opensea.io/XXX',
  DOUBAN: 'https://www.douban.com/people/nocower',
  DOUBAN_MOVIE: 'https://movie.douban.com/people/nocower/collect',
  LINKEDIN: 'https://www.linkedin.com/in/XXX',
  INSTAGRAM: `https://www.instagram.com/${IDENTITIES.INSTAGRAM_USERNAME}`,
  TWITTER: `https://twitter.com/${IDENTITIES.TWITTER_USER_NAME}`,
});
